defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "max"
  save_top_k: 1
  save_last: True
  verbose: False

early_stopping:
  monitor: "val/acc"
  patience: 100
  mode: "max"
  min_delta: 0.00

model_summary:
  max_depth: -1